# Changes here will be overwritten by Copier
_commit: 4.0.1
_src_path: https://github.com/DiamondLightSource/python-copier-template
author_email: dominic.oram@diamond.ac.uk
author_name: Dominic Oram
component_lifecycle: production
component_owner: group:data-acquisition
component_type: library
description: Ophyd devices and other utils that could be used across DLS beamlines
distribution_name: dls-dodal
docker: false
docs_type: sphinx
git_platform: github.com
github_org: DiamondLightSource
package_name: dodal
pypi: true
repo_name: dodal
strict_typing: false
type_checker: pyright
