repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-merge-conflict

  # Automatic source code formatting
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--safe, --quiet]
        files: \.pyi?
        types: [file]

  - repo: local
    hooks:
      - id: ruff
        name: Run ruff
        stages: [commit]
        language: system
        entry: ruff
        types: [python]
        
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        files: 'src/.*\.py$'
        additional_dependencies: [types-requests, pydantic]
        args: ["--ignore-missing-imports", "--no-strict-optional"]
