repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-merge-conflict

  # Automatic source code formatting
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--safe, --quiet]
        files: \.pyi?
        types: [file]

  # Sort imports
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args:
          [
            "--profile=black",
            '--add_imports="from __future__ import annotations',
          ]

  # Linting
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          ["flake8-comprehensions==3.8.0", "Flake8-pyproject"]
        args: ["--max-line-length=88", "--ignore=E203,F811,F722,E501,W503,C408"]

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        files: 'src/.*\.py$'
        additional_dependencies: [types-requests, pydantic]
        args: ["--ignore-missing-imports", "--no-strict-optional"]
