apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dls-dodal
  title: dodal
  description: Ophyd devices and other utils that could be used across DLS beamlines
spec:
  type: library
  lifecycle: production
  owner: group:data-acquisition
  dependsOn:
    - zocalo
