from collections.abc import Iterable, Sequence
from decimal import Decimal
from typing import TypeVar, cast

import numpy as np
from bluesky.protocols import HasName

from dodal.plans.scans.types import (
    MovableListOfPoints,
    MovableStartStep,
    MovableStartStopNum,
    MovableStartStopStep,
    Number,
)

T = TypeVar("T")


def flatten(items: Iterable[Iterable[T]]) -> tuple[T, ...]:
    """Flatten one level of nested iterables."""
    return tuple(item for group in items for item in group)


def get_bluesky_obj_name(obj) -> str:
    return obj.name if isinstance(obj, HasName) else repr(obj)


def make_list_scan_shape(
    params: Sequence[MovableListOfPoints], grid: bool
) -> tuple[int, ...]:
    shape = []
    for param in params:
        points = param[1]
        # List arg must all be same size. If list missing or not same size, this will
        # be validated by bp.list_scan.
        dim = len(points)
        shape.append(dim)
        if not grid:
            break

    return tuple(shape)


def _decimal_places(value: Number) -> int:
    """Return the number of decimal places represented by a numeric value.

    Uses the decimal representation of the value to avoid floating-point
    representation artefacts when determining its precision.
    """
    exponent = cast(int, Decimal(str(value)).as_tuple().exponent)
    return max(0, -exponent)


def _round_list_elements(
    values: list[Number],
    params: list[Number],
) -> list[Number]:
    """Round values to the greatest decimal precision of the given parameters.

    This prevents floating-point arithmetic from producing values such as
    ``0.30000000000000004`` when generating scan points.

    Args:
        values: Values to round.
        params: Input parameters whose decimal precision determines the
            rounding precision.
    """
    decimal_places = max(_decimal_places(param) for param in params)
    return [round(value, decimal_places) for value in values]


def _make_stepped_list_step(values: MovableStartStopStep) -> list[Number]:
    """Generate a list of points between start and stop using a step size.

    The step direction is adjusted to match the direction from start to stop.
    If the step would exceed the total range, it is reduced to the range.
    The stop value is included when the next step falls within 5% of the
    requested step size.

    The resulting values are rounded to the greatest decimal precision of
    the input parameters to avoid floating-point representation artefacts.

    Args:
        values: A tuple containing the movable, start position, stop position,
            and step size.

    Returns:
        A list of generated scan positions.
    """
    movable, start, stop, step = values

    if step == 0:
        raise ValueError(
            f"Step size cannot be 0. "
            "Expected (movable, start, stop, step). "
            f"Received ({get_bluesky_obj_name(movable)}, {start}, {stop}, {step})."
        )
    if start == stop:
        raise ValueError(
            f"Start and stop values cannot be the same. "
            "Expected (movable, start, stop, step). "
            f"Received ({get_bluesky_obj_name(movable)}, {start}, {stop}, {step})."
        )
    if abs(step) > abs(stop - start):
        step = stop - start

    step = abs(step) * np.sign(stop - start)
    stepped_list = np.arange(start, stop, step).tolist()

    if abs((stepped_list[-1] + step) - stop) <= abs(step * 0.05):
        stepped_list.append(stepped_list[-1] + step)

    rounded_stepped_list = _round_list_elements(stepped_list, [start, stop, step])
    return rounded_stepped_list


def _make_stepped_list_num(values: MovableStartStopNum) -> list[Number]:
    """Generate a list of points from a start position using a fixed count.

    Points are generated by repeatedly adding the step size to the starting
    position. The resulting values are rounded to the greatest decimal
    precision of the input parameters to avoid floating-point representation
    artefacts.

    Args:
        values: A tuple containing the movable, start position, stop position,
            and number of points.

    Returns:
        A list containing ``num`` scan positions.

    Raises:
        ValueError: If ``step`` or ``num`` is zero.
    """
    movable, start, step, num = values
    if num == 0 or step == 0:
        raise ValueError(
            "Number of steps and number of points cannot be zero. "
            "Expected (movable, start, step, num). "
            f"Received ({get_bluesky_obj_name(movable)}, {start}, {step}, {num})."
        )
    stepped_list = [start + (n * step) for n in range(num)]
    rounded_stepped_list = _round_list_elements(stepped_list, [start, step])
    return rounded_stepped_list


def make_step_scan_args_and_shape(
    trajectory: MovableStartStopStep, extra_trajectories: Sequence[MovableStartStep]
) -> tuple[list[MovableListOfPoints], tuple[int, ...]]:
    """Generate list-scan arguments for a step scan.

    The first trajectory defines the scan range and number of points using
    ``(movable, start, stop, step)``. Additional trajectories use
    ``(movable, start, step)`` and are generated with the same number of
    points as the first trajectory.

    This produces the list of [movable, [point1, point2, ...]] arguments required by
    ``bluesky.plans.list_scan`` and the corresponding scan shape.

    Args:
        trajectory: Primary trajectory defining the scan range and number of
            points.
        extra_trajectories: Additional trajectories. Each is generated with
            the same number of points as the primary trajectory.

    Returns:
        A tuple containing the generated ``(movable, points)`` arguments and
        the scan shape. The shape contains a single dimension corresponding to the
        number of points in the primary trajectory.
    """
    movable, _, _, _ = trajectory
    movable_values = _make_stepped_list_step(trajectory)
    shape = [len(movable_values)]
    step_scan_args: list[MovableListOfPoints] = [(movable, movable_values)]

    for extra_t in extra_trajectories:
        movable, start, step = extra_t
        # For a non-grid scan, subsequent axes have the same number
        # of points as the first axis.
        movable_values = _make_stepped_list_num((movable, start, step, shape[0]))
        step_scan_args.append((movable, movable_values))

    return step_scan_args, tuple(shape)


def make_step_grid_scan_args_and_shape(
    params: Sequence[MovableStartStopStep],
) -> tuple[list[MovableListOfPoints], tuple[int, ...]]:
    """Generate list-grid-scan arguments for a stepped grid scan.

    Each trajectory defines an independent scan axis using
    ``(movable, start, stop, step)``. The number of generated points for each
    trajectory determines the corresponding dimension of the scan shape.

    This produces the list of [movable, [point1, point2, ...]] arguments required by
    ``bluesky.plans.list_grid_scan`` and the corresponding multidimensional
    scan shape.

    Args:
        params: Trajectories defining the scan axes. Each trajectory consists
            of a movable, start position, stop position, and step size.

    Returns:
        A tuple containing a list of the generated movable with the list of points and
        the scan shape, with one dimension for each trajectory.
    """
    step_scan_args: list[MovableListOfPoints] = []
    shape: list[int] = []
    try:
        for trajectory in params:
            movable, _, _, _ = trajectory
            movable_values = _make_stepped_list_step(trajectory)
            shape.append(len(movable_values))
            step_scan_args.append((movable, movable_values))

        return step_scan_args, tuple(shape)

    except Exception as e:
        raise ValueError("Recieved input ") from e
