on:
  workflow_call:

jobs:
  license_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Get explicit and transitive dependencies
        run: |
          pip install
          pip freeze > requirements-all.txt
      - name: Check python
        id: license_check_report
        uses: pilosus/action-pip-license-checker@v2
        with:
          requirements: "requirements-all.txt"
          fail: "Copyleft"
          exclude: "(?i)^(pylint|aio[-_]*).*"
      - name: Print report
        if: ${{ always() }}
        run: echo "${{ steps.license_check_report.outputs.report }}"

  get_report:
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies license compliance checker
        id: license_check_report
        uses: pilosus/action-pip-license-checker@cc7a461bfa27b44ad187b8578c881ef5138c13fd
        with:
          external: "licenses.csv"
          external-format: "csv"
          external-options: "{:skip-header false :package-column-index 0 :license-column-index 2}"
          report-format: "json-pretty"
          formatter: "%-65s %-65s %-20s %-40s"
          totals: true
          headers: true
          fail: "StrongCopyleft,NetworkCopyleft,Other,Error"
          verbose: 1
      - name: Save report
        if: ${{ always() }}
        run: echo "${{ steps.license_check_report.outputs.report }}" > license-report.json
      - name: Upload artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: license-report
          path: license-report.json
