on:
  workflow_call:
    inputs:
      tox:
        type: string
        description: What to run under tox
        required: true


jobs:
  run:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install python packages
        uses: ./.github/actions/install_requirements

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: x64
      
      - name: Install import linter
        run: pip install import-linter

      - name: Run import linter
        run: lint-imports

      - name: Run tox
        run: tox -e ${{ inputs.tox }}
